# Generated by Django 3.0.2 on 2020-01-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20200130_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business_num',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=10),
        ),
    ]
