# Generated by Django 3.0.2 on 2020-01-30 06:04

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=11)),
                ('information', models.TextField()),
                ('operating_time', django_mysql.models.JSONField(default=dict)),
                ('min_price', models.PositiveIntegerField()),
                ('grade', models.DecimalField(decimal_places=1, max_digits=2)),
                ('delivery_time', models.TimeField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myauth.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('grade', models.SmallIntegerField()),
                ('image', django_mysql.models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laundryshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.LaundryShop')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauth.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laundryshop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laundry.LaundryShop')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myauth.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='LaundryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('laundry_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.LaundryShop')),
            ],
        ),
    ]
