# Generated by Django 3.0.2 on 2020-01-30 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundryshop',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='laundryshop',
            name='delivery_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
