# Generated by Django 3.0.2 on 2020-01-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0003_auto_20200130_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundryshop',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='like',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='review',
            name='profile',
        ),
    ]
